---
settings:
  # https://macos-defaults.com/
  # key
  - {
      # キーリピートの速度
      domain: NSGlobalDomain,
      key: KeyRepeat,
      type: int,
      value: 2,
    }
  - {
      # キーリピート開始までのタイミング
      domain: NSGlobalDomain,
      key: InitialKeyRepeat,
      type: int,
      value: 15,
    }
  - {
      # US モードでキーリピートする
      domain: NSGlobalDomain,
      key: ApplePressAndHoldEnabled,
      type: bool,
      value: false,
    }
  - {
      # 自動大文字の無効化
      domain: NSGlobalDomain,
      key: NSAutomaticCapitalizationEnabled,
      type: bool,
      value: false,
    }
  - {
      # スペルの訂正を無効にする
      domain: NSGlobalDomain,
      key: NSAutomaticSpellingCorrectionEnabled,
      type: bool,
      value: false,
    }
  # dock
  - {
      # Dock を自動的に隠す
      domain: com.apple.dock,
      key: autohide,
      type: bool,
      value: true,
    }
  - {
      # Dock の拡大機能を入にする
      domain: com.apple.dock,
      key: magnification,
      type: bool,
      value: true,
    }
  - {
      # 起動中のアプリケーションをアニメーションで表示させない
      domain: com.apple.dock,
      key: launchanim,
      type: bool,
      value: false,
    }
  - {
      # 起動中のアプリアイコンにインジケータを表示させない
      domain: com.apple.dock,
      key: show-process-indicators,
      type: bool,
      value: false,
    }
  - {
      # 最近使ったアプリアイコンを表示させない
      domain: com.apple.dock,
      key: show-recents,
      type: bool,
      value: false,
    }
  # finder
  - {
      # パスバーを表示する
      domain: com.apple.finder,
      key: ShowPathbar,
      type: bool,
      value: true,
    }
  - {
      # ステータスバーを表示する
      domain: com.apple.finder,
      key: ShowStatusBar,
      type: bool,
      value: true,
    }
  - {
      # ゴミ箱を空にする前の警告を無効化する
      domain: com.apple.finder,
      key: WarnOnEmptyTrash,
      type: bool,
      value: true,
    }
  - {
      # デフォルトで隠しファイルを表示する
      domain: com.apple.finder,
      key: AppleShowAllExtensions,
      type: bool,
      value: true,
    }
  - {
      # 全ての拡張子のファイルを表示する
      domain: NSGlobalDomain,
      key: AppleShowAllExtensions,
      type: bool,
      value: true,
    }
  - {
      # スクロールバーを常時表示する
      domain: NSGlobalDomain,
      key: AppleShowScrollBars,
      type: string,
      value: Always,
    }
  - {
      # スクリーンキャプチャの影をなくす
      domain: com.apple.screencapture,
      key: disable-shadow,
      type: bool,
      value: true,
    }
  - {
      # スクリーンショットの保存形式を PNG にする
      domain: com.apple.screencapture,
      key: type,
      type: string,
      value: png,
    }
  - {
      # QuickLook で文字の選択、コピーを出来るようにする
      domain: com.apple.finder,
      key: QLEnableTextSelection,
      type: bool,
      value: true,
    }
  - {
      # 名前で並べ替えを選択時にディレクトリを前に置くようにする
      domain: com.apple.finder,
      key: FXDefaultSearchScop,
      type: string,
      value: SCcf,
    }
  - {
      # ディレクトリのスプリングロードを有効化
      domain: NSGlobalDomain,
      key: com.apple.springing.enabled,
      type: bool,
      value: true,
    }
  - {
      # スプリングロード遅延を除去
      domain: NSGlobalDomain,
      key: com.apple.springing.delay,
      type: float,
      value: 0.5,
    }
  - {
      # ダウンロードしたファイルを初めて開く際に表示される警告ダイアログを無効
      domain: com.apple.LaunchServices,
      key: LSQuarantine,
      type: bool,
      value: false,
    }
  - {
      # 拡張子変更時の警告を無効化
      domain: com.apple.finder,
      key: FXEnableExtensionChangeWarning,
      type: bool,
      value: false,
    }
  - {
      # 最近使ったタグを無効化
      domain: com.apple.finder,
      key: ShowRecentTags,
      type: bool,
      value: false,
    }
  - {
      # 外部ディスクのデスクトップ表示を無効化
      domain: com.apple.finder,
      key: ShowExternalHardDrivesOnDesktop,
      type: bool,
      value: false,
    }
  - {
      # リムーバブルディスクのデスクトップ表示を無効化
      domain: com.apple.finder,
      key: ShowRemovableMediaOnDesktop,
      type: bool,
      value: false,
    }
  - {
      # マウントされたサーバーのデスクトップ表示を無効化
      domain: com.apple.finder,
      key: ShowMountedServersOnDesktop,
      type: bool,
      value: false,
    }
  - {
      # 新規finderでの表示
      domain: com.apple.finder,
      key: NewWindowTargetPath,
      type: string,
      value: !unsafe "file://${HOME}",
    }
  - {
      # ゴミ箱を30日で殻にしない
      domain: com.apple.finder,
      key: FXRemoveOldTrashItems,
      type: bool,
      value: false,
    }
  # menu bar
  - {
      # 時間フォーマット
      domain: com.apple.menuextra.clock,
      key: DateFormat,
      type: string,
      value: '"EEE d MMM HH:mm:ss"',
    }
  # other
  - {
      # ターミナル終了時のプロンプトを非表示にする
      domain: com.googlecode.iterm2,
      key: PromptOnQuit,
      type: bool,
      value: false,
    }
  - {
      # ターミナルのベルを停止
      domain: com.apple.terminal,
      key: Bell,
      type: bool,
      value: false,
    }
  - {
      # ターミナルヴィジュアルベルを停止
      domain: com.apple.terminal,
      key: VisualBell,
      type: bool,
      value: false,
    }
  - {
      # VSCode で長押しで移動1
      domain: com.microsoft.VSCode,
      key: ApplePressAndHoldEnabled,
      type: bool,
      value: false,
    }
  - {
      # VSCode で長押しで移動2
      domain: com.microsoft.VSCodeInsiders,
      key: ApplePressAndHoldEnabled,
      type: bool,
      value: false,
    }
