---
- block:
    - block:
        # osx defaults
        - name: set osx defaults
          osx_defaults:
            domain: "{{ item.domain }}"
            key: "{{ item.key }}"
            type: "{{ item.type }}"
            value: "{{ item.value }}"
          with_items: "{{ settings }}"
      tags:
        - osx_defaults

    - block:
        # Ricty
        - name: fix Ricty Font for VSCode
          shell: |
            brew link fontforge
            chmod a+x ./scripts/fix_ricty.pe
            ./scripts/fix_ricty.pe ~/Library/Fonts/RictyDiminished-Bold.ttf
            ./scripts/fix_ricty.pe ~/Library/Fonts/RictyDiminished-Regular.ttf
            ./scripts/fix_ricty.pe ~/Library/Fonts/RictyDiminishedDiscord-Bold.ttf
            ./scripts/fix_ricty.pe ~/Library/Fonts/RictyDiminished-Regular.ttf
      tags:
        - ricty

    - block:
        # clone Prezto zsh plugin
        - name: remove zshsetting
          shell: |
            rm ~/.zlogin
            rm ~/.zlogout
            rm ~/.zpreztorc
            rm ~/.zprofile
            rm ~/.zshenv
            rm ~/.zshrc

        - name: install prezto
          shell: 'git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"'
          ignore_errors: yes
      tags:
        - zsh
  tags:
    - macos
