---
- block:
    - block:
        # osx defaults
        - name: set osx defaults
          osx_defaults:
            domain: "{{ item.domain }}"
            key: "{{ item.key }}"
            type: "{{ item.type }}"
            value: "{{ item.value }}"
          with_items: "{{ settings }}"
      tags:
        - osx_defaults

    - block:
        # clone Prezto zsh plugin
        - name: remove zshsetting
          shell: |
             rm ~/.zlogin
             rm ~/.zlogout
             rm ~/.zpreztorc
             rm ~/.zprofile
             rm ~/.zshenv
             rm ~/.zshrc

        - name: install prezto
          shell: 'git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"'
      tags:
        - zsh
  tags:
    - macos
