---
- block:
    - block:
        # osx defaults
        - name: set osx defaults
          osx_defaults:
            domain: "{{ item.domain }}"
            key: "{{ item.key }}"
            type: "{{ item.type }}"
            value: "{{ item.value }}"
          with_items: "{{ settings }}"

        - name: disable the sound effects on boot
          command: sudo /usr/sbin/nvram SystemAudioVolume=" "

        - name: Show the /Volumes folder
          command: sudo chflags nohidden /Volumes

        - name: Disable auto power off when power is connected
          command: sudo /usr/sbin/nvram BootPreference=%00
      tags:
        - osx_defaults

    - block:
        # clone Prezto zsh plugin
        - name: remove zshsetting
          shell: |
            rm ~/.zlogin
            rm ~/.zlogout
            rm ~/.zpreztorc
            rm ~/.zprofile
            rm ~/.zshenv
            rm ~/.zshrc

        - name: install prezto
          shell: 'git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"'
          ignore_errors: yes
      tags:
        - zsh
  tags:
    - macos
