---
- block:
    - name: homebrew cask install
      homebrew_cask:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        install_options: "appdir=/Applications"
      register: result
      ignore_errors: true # インストール済みだった場合止まるのでスルー
      with_items: "{{ packages }}"

  tags:
    - homebrew_cask
