---
- block:
    # brew update
    - name: homebrew update/upgrade
      homebrew:
        update_homebrew: true
        upgrade_all: no
    - name: homebrew cask install
      homebrew_cask:
        name: "{{ item.name }}"
        state: "{{ item.state  | default('installed')}}"
        install_options: "appdir=~/Applications"
      register: result
      ignore_errors: yes # インストール済みだった場合止まるのでスルー
      with_items: "{{ packages }}"

  tags:
    - homebrew_cask
