---
- block:
    # git clone
    - name: git clone dotfiles
      git: repo="{{ dotfiles.repository }}" dest="{{ dotfiles.dest }}"

    # symlink
    - name: symlink dotfiles
      shell: "{{ dotfiles .symlink_command }}"

  tags: dotfiles
